### ISSUE TITLE
Querying data Error

### ISSUE THREAD

**Issue by MFS05Maledixion** [kavir1698/DietRecommender.jl#1]
I keep getting this error. I tried to open the file vs code points to edit it, but it seems its readonly and is a package.

::ERROR::

julia> include("./main.jl")

`Querying the database...`
`ERROR: LoadError: ArgumentError: syntax df[column] is not supported use df[!, column] instead
Stacktrace:`
`[1] getindex(#unused#::DataFrames.DataFrame, #unused#::Int64)
   @ DataFrames C:\Users\kamva\.julia\packages\DataFrames\LteEl\src\abstractdataframe`
`\abstractdataframe.jl:2448
 [2] apply_updates(food_des::DataFrames.DataFrame, nut_data::DataFrames.DataFrame, updatedir::String)
   @ Main.DietRecommender C:\Users\kamva\Desktop\DEV WORKSPACES\SCHOOL DEV\test_projects`
`\DietRecommender.jl\src\get_data.jl:97
 [3] allnutdata(; data_folder::String, dri_file::String, updatedir::String)
   @ Main.DietRecommender C:\Users\kamva\Desktop\DEV WORKSPACES\SCHOOL DEV\test_projects`
`\DietRecommender.jl\src\get_data.jl:203
 [4] loaddata(your_age::Int64, your_sex::String, your_weight::Int64; only_groups::Vector{Int64})
   @ Main.DietRecommender C:\Users\kamva\Desktop\DEV WORKSPACES\SCHOOL DEV\test_projects`
`\DietRecommender.jl\src\get_data.jl:333
 [5] get_diet(your_age::Int64, your_sex::String, your_weight::Int64; only_groups::Vector{Int64}, exclude_food::Vector{String}, excluded_nutrients::Vector{Any})
   @ Main.DietRecommender C:\Users\kamva\Desktop\DEV WORKSPACES\SCHOOL DEV\test_projects`
`\DietRecommender.jl\src\return_diet.jl:79
 [6] get_diet(your_age::Int64, your_sex::String, your_weight::Int64)
   @ Main.DietRecommender C:\Users\kamva\Desktop\DEV WORKSPACES\SCHOOL DEV\test_projects\DietRecommender.jl`
`\src\return_diet.jl:76
 [7] top-level scope
   @ C:\Users\kamva\Desktop\DEV WORKSPACES\SCHOOL DEV\test_projects\DietRecommender.jl\main.jl:8`
`[8] include(fname::String)
   @ Base.MainInclude .\client.jl:476`
`[9] top-level scope
   @ REPL[1]:1`
`in expression starting at C:\Users\kamva\Desktop\DEV WORKSPACES\SCHOOL DEV\test_projects\DietRecommender.jl\main.jl:8`

**Comment by kavir1698** [comment]
I have updated the package. It should work now. Feel free to reopen
